### ISSUE TITLE
这次更新后有个依赖找不到

### ISSUE THREAD

**Issue by BEEL-Golfos** [Megghy/MultiSEngine#7]
发现好像编译有问题，但是没找到依赖

**Comment by BEEL-Golfos** [comment]
请问该怎么编译，我编译的时候发现有问题，但是手动把依赖放进去还是不行

**Comment by Megghy** [comment]
具体？

**Comment by BEEL-Golfos** [comment]
我自己编译了一个，但是我用v1.4.0.5.2 进 v1.4.3.2 报错如下
 [Warn] Client recieve loop abnormally terminated.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at TrProtocol.PacketSerializer.ArraySerializer._Read(BinaryReader br)
   at TrProtocol.FieldSerializer`1.Read(BinaryReader br)
   at TrProtocol.PacketSerializer.<>c__DisplayClass10_1.<GenerateSerializers>b__5(Object o, BinaryReader br)
   at TrProtocol.PacketSerializer.<>c__DisplayClass11_0.<RegisterPacket>b__2(BinaryReader br)
   at TrProtocol.PacketSerializer.Deserialize(BinaryReader br0)
   at MultiSEngine.Core.Adapter.BaseAdapter.RecieveLoop()

请问是我编译的有问题还是……

**Comment by Megghy** [comment]
trprotocol里的arrayserializer有个数组的处理有点问题 我在我本地的库里修过但是没提pr

**Comment by BEEL-Golfos** [comment]
还是没有找到解决办法 /哭了

**Comment by Megghy** [comment]
你是想弄什么需要自己编译
