### ISSUE TITLE
添加对新版本的支持

### ISSUE THREAD

**Issue by F-fengzi** [Megghy/MultiSEngine#8]
当前版本无论开不开 Crossplay 都无法用 248 (v1.4.3.6) 连接

顺便建议加一个强制允许不同版本连接的选项，~~因为mse更新看起来会很不及时的样子~~

**Comment by F-fengzi** [comment]
错误日志 如果会有用的话
```
[Error] An error occurred while processing packet TrProtocol.Packets.ClientHello.
System.Collections.Generic.KeyNotFoundException: The given key '248' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MultiSEngine.Core.Adapter.BaseAdapter.get_InternalServerSerializer()
   at MultiSEngine.Core.Adapter.BaseAdapter.InternalSendPacket(Packet packet, Boolean asClient)
   at MultiSEngine.Core.Adapter.FakeWorldAdapter.GetPacket(Packet packet)
   at MultiSEngine.Core.Adapter.BaseAdapter.ProcessPacketLoop()
```

**Comment by Megghy** [comment]
已更新 原本就允许强制进不过代码没写对

**Comment by F-fengzi** [comment]
好快！谢谢

**Comment by F-fengzi** [comment]
加入之后 连接的世界都是空的 不停往下掉是什么原因

**Comment by Megghy** [comment]
输 `test 世界名 -detail` 看看

**Comment by F-fengzi** [comment]
```
[Info] Start testing the connectivity of [test1]
[TEST] <test1> TESTING: 0 - Start connecting to [test1]<127.0.0.1:7778>
[TEST] <test1> TESTING: 1 - Sending [ConnectRequest] packet
[TEST] <test1> TESTING: 2 - Sending [PlayerInfo] packet
[TEST] <test1> TESTING: 2 - Sending [UUID] packet
[TEST] <test1> TESTING: 2 - Requesting world data
[TEST] <test1> TESTING: 4 - Requesting map data
[TEST] <test1> TESTING: 4 - Requesting spawn player
[TEST] <test1> Test FAILED: Time out
esetil
[Info] Start testing the connectivity of [test2]
[TEST] <test2> TESTING: 0 - Start connecting to [test2]<127.0.0.1:7779>
[TEST] <test2> TESTING: 1 - Sending [ConnectRequest] packet
[TEST] <test2> TESTING: 2 - Sending [PlayerInfo] packet
[TEST] <test2> TESTING: 2 - Sending [UUID] packet
[TEST] <test2> TESTING: 2 - Requesting world data
[TEST] <test2> TESTING: 4 - Requesting map data
[TEST] <test2> TESTING: 4 - Requesting spawn player
[TEST] <test2> SUCCESS: 10 - Server authentication completed, allow client to start running
[Success] Server [test2] is in good condition :)
```

显示第二个成功，但两个的效果都是一样

**Comment by Megghy** [comment]
ts和mse都没报错吗 我自己测没问题
还是说你没输/mse tp 传送过去

**Comment by F-fengzi** [comment]
没有报错，单独进那两个服务器也没问题，也可以list出来
用了tp，可以进去世界但里面是空的

顺便一提我在用原版服不是tshock, 不知道有没有关系

**Comment by Megghy** [comment]
还是没复现出来

**Comment by F-fengzi** [comment]
看起来游戏服务器那边加入时现在有了有这个报错
```
127.0.0.1:59406 is connecting...
127.0.0.1:59406 was booted: Invalid operation at this state.
127.0.0.1:59572 is connecting...
127.0.0.1:59572 was booted: Invalid operation at this state.
127.0.0.1:59682 is connecting...
127.0.0.1:59682 was booted: Invalid operation at this state.
127.0.0.1:59686 is connecting...
127.0.0.1:59686 was booted: Invalid operation at this state.
127.0.0.1:59702 is connecting...
127.0.0.1:59702 was booted: Invalid operation at this state.
```
它是官方服1.4.3.6

**Comment by F-fengzi** [comment]
Config.json
```
{
  "ListenIP": "0.0.0.0",
  "ListenPort": 7777,
  "ServerName": "Test Server",
  "ServerVersion": 248,
  "Token": "114514",
  "SwitchTimeOut": 5000,
  "EnableCrossplayFeature": true,
  "EnableChatForward": true,
  "SwitchToDefaultServerOnJoin": true,
  "RestoreDataWhenJoinNonSSC": true,
  "DefaultServer": "test1",
  "Servers": [
    {
      "Visible": true,
      "Name": "test1",
      "ShortName": "t1",
      "IP": "127.0.0.1",
      "Port": 7778,
      "SpawnX": -1,
      "SpawnY": -1,
      "VersionNum": 248
    },
    {
      "Visible": true,
      "Name": "test2",
      "ShortName": "t2",
      "IP": "127.0.0.1",
      "Port": 7779,
      "SpawnX": -1,
      "SpawnY": -1,
      "VersionNum": 248
    }
  ]
}
```

**Comment by F-fengzi** [comment]
有一点比较奇怪，测试test1是time out, test 2是success

**Comment by F-fengzi** [comment]
重启之后重试有新的报错！mse这边
把我可以知道的信息都发过来
```
[Log] 114.514.191.981:23067 trying to connect...
[Info] Version of 114.514.191.981:23067 is v1.4.3.6<248>.
[Info] Switching [Troll] to the server: [test1]
[Log] Syncing player: [Troll]
[Error] An error occurred while processing packet TrProtocol.Packets.WorldData.
System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at MultiSEngine.Core.Adapter.BaseAdapter.InternalSendPacket(Packet packet, Boolean asClient)
   at MultiSEngine.Core.Adapter.VisualPlayerAdapter.GetPacket(Packet packet)
   at MultiSEngine.Core.Adapter.BaseAdapter.ProcessPacketLoop()
[Chat] Troll <test1>: /mse tp test2
[Info] Switching [Troll] to the server: [test2]
[Log] Syncing player: [Troll]
[Error] An error occurred while processing packet TrProtocol.Packets.WorldData.
System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at MultiSEngine.Core.Adapter.BaseAdapter.InternalSendPacket(Packet packet, Boolean asClient)
   at MultiSEngine.Core.Adapter.VisualPlayerAdapter.GetPacket(Packet packet)
   at MultiSEngine.Core.Adapter.BaseAdapter.ProcessPacketLoop()
[Log] [Troll] disconnected.
```

**Comment by F-fengzi** [comment]
最近又试了试 结果都如上

上面把我能给的信息都尽量详细提供了
然后服务器是arm64的，装的dotnet6

**Comment by Megghy** [comment]
我并没有arm64的机子所以大概没法调试, 搜了一下似乎是机器的问题
只能建议换个运行环境或者换dimensions之类的项目

**Comment by F-fengzi** [comment]
好吧谢谢
可以换到什么运行环境
dimensions可以给个链接嘛w

**Comment by Megghy** [comment]
不是arm64的
https://github.com/popstarfreas/Dimensions

**Comment by F-fengzi** [comment]
ah那暂时换不了
谢谢谢谢！
